spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa

  h2:
    console:
      enabled: true